### ISSUE TITLE
`cosmiconfig is not a function` Does not work in version 1.0.3

### ISSUE THREAD

**Issue by tw666** [rfgamaral/parcel-plugin-typings-for-css-modules#27]
After I introduced this plugin, I get an error.
```
🚨  cosmiconfig is not a function
    at new TypedCssModules (/User/xxx/xxx/node_modules/@rfgamaral/parcel-plugin-typings-for-css-modules/lib/asset.js:13:26)
    at Parser.getAsset (/User/xxx/xxx/node_modules/parcel-bundler/src/Parser.js:102:12)
    at Bundler.getLoadedAsset (/User/xxx/xxx/node_modules/parcel-bundler/src/Bundler.js:442:29)
    at Bundler.resolveAsset (/User/xxx/xxx/node_modules/parcel-bundler/src/Bundler.js:434:17)
    at async Bundler.resolveDep (/User/xxx/xxx/node_modules/parcel-bundler/src/Bundler.js:484:14)
    at async /User/xxx/xxx/node_modules/parcel-bundler/src/Bundler.js:608:26
    at async Promise.all (index 1)
    at async Bundler.loadAsset (/User/xxx/xxx/node_modules/parcel-bundler/src/Bundler.js:599:21)
    at async /User/xxx/xxx/node_modules/parcel-bundler/src/Bundler.js:610:13
    at async Promise.all (index 0)
```

It seems that `cosmiconfig` has changed API after version 6.0
